# Generated by Django 6.0.3 on 2026-05-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bank_account_holder",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_country",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_currency",
            field=models.CharField(blank=True, default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_deposit_instructions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="bank_routing_or_swift",
            field=models.CharField(
                blank=True,
                help_text="Routing number, sort code, SWIFT/BIC, or IBAN as applicable.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_transfer",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the user can submit local bank deposit requests using assigned bank details.",
            ),
        ),
    ]
