# Generated by Django 6.0.2 on 2026-05-22 12:00

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[400, 400],
                upload_to="documents/profile_pictures",
                verbose_name="Profile picture",
            ),
        ),
    ]
