from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("NGN", "Nigerian Naira"),
                    ("GHS", "Ghanaian Cedi"),
                    ("KES", "Kenyan Shilling"),
                    ("ZAR", "South African Rand"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("JPY", "Japanese Yen"),
                    ("CNY", "Chinese Yuan"),
                    ("INR", "Indian Rupee"),
                    ("AED", "UAE Dirham"),
                    ("SAR", "Saudi Riyal"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MXN", "Mexican Peso"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Zloty"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("NZD", "New Zealand Dollar"),
                    ("PHP", "Philippine Peso"),
                    ("THB", "Thai Baht"),
                    ("IDR", "Indonesian Rupiah"),
                    ("MYR", "Malaysian Ringgit"),
                    ("EGP", "Egyptian Pound"),
                    ("TTD", "Trinidad and Tobago Dollar"),
                    ("KYD", "Cayman Islands Dollar"),
                ],
                default="USD",
                help_text="Account display currency for balances and transfers.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bank_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("NGN", "Nigerian Naira"),
                    ("GHS", "Ghanaian Cedi"),
                    ("KES", "Kenyan Shilling"),
                    ("ZAR", "South African Rand"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("JPY", "Japanese Yen"),
                    ("CNY", "Chinese Yuan"),
                    ("INR", "Indian Rupee"),
                    ("AED", "UAE Dirham"),
                    ("SAR", "Saudi Riyal"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MXN", "Mexican Peso"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Zloty"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("NZD", "New Zealand Dollar"),
                    ("PHP", "Philippine Peso"),
                    ("THB", "Thai Baht"),
                    ("IDR", "Indonesian Rupiah"),
                    ("MYR", "Malaysian Ringgit"),
                    ("EGP", "Egyptian Pound"),
                    ("TTD", "Trinidad and Tobago Dollar"),
                    ("KYD", "Cayman Islands Dollar"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
