# Generated by Django 6.0.3 on 2026-05-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="crypto_amount",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="crypto_symbol",
            field=models.CharField(
                blank=True,
                choices=[("BTC", "Bitcoin"), ("ETH", "Ethereum"), ("USDT", "Tether")],
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="proof_image",
            field=models.ImageField(
                blank=True, upload_to="transactions/deposit_proofs/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                    ("GBP", "British Pound"),
                    ("NGN", "Nigerian Naira"),
                    ("GHS", "Ghanaian Cedi"),
                    ("KES", "Kenyan Shilling"),
                    ("ZAR", "South African Rand"),
                    ("CAD", "Canadian Dollar"),
                    ("AUD", "Australian Dollar"),
                    ("CHF", "Swiss Franc"),
                    ("JPY", "Japanese Yen"),
                    ("CNY", "Chinese Yuan"),
                    ("INR", "Indian Rupee"),
                    ("AED", "UAE Dirham"),
                    ("SAR", "Saudi Riyal"),
                    ("SGD", "Singapore Dollar"),
                    ("HKD", "Hong Kong Dollar"),
                    ("BRL", "Brazilian Real"),
                    ("MXN", "Mexican Peso"),
                    ("TRY", "Turkish Lira"),
                    ("PLN", "Polish Zloty"),
                    ("SEK", "Swedish Krona"),
                    ("NOK", "Norwegian Krone"),
                    ("DKK", "Danish Krone"),
                    ("NZD", "New Zealand Dollar"),
                    ("PHP", "Philippine Peso"),
                    ("THB", "Thai Baht"),
                    ("IDR", "Indonesian Rupiah"),
                    ("MYR", "Malaysian Ringgit"),
                    ("EGP", "Egyptian Pound"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
    ]
