from django.urls import reverse_lazy
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_LOGOUT_REDIRECT_URL = reverse_lazy("konnect:dashboard")
ACCOUNT_LOGIN_REDIRECT_URL = "/dashboard/"
ACCOUNT_SIGNUP_REDIRECT_URL = reverse_lazy("konnect:settings")
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = ACCOUNT_LOGIN_REDIRECT_URL
ACCOUNT_FORMS = {"signup": "konnect.forms.CustomSignupForm"}
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Konnect] "
