# Generated by Django 6.0.3 on 2026-05-21 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("card_name", models.CharField(max_length=64)),
                (
                    "network",
                    models.CharField(
                        choices=[("visa", "Visa"), ("mastercard", "Mastercard")],
                        max_length=16,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("teal-gold", "Teal & Gold"),
                            ("midnight", "Midnight"),
                            ("sunset", "Sunset"),
                            ("ocean", "Ocean"),
                            ("royal", "Royal"),
                            ("carbon", "Carbon"),
                        ],
                        default="teal-gold",
                        max_length=16,
                    ),
                ),
                ("last_four_digits", models.CharField(max_length=4)),
                ("expiry_date", models.CharField(max_length=7)),
                ("is_frozen", models.BooleanField(default=False)),
                (
                    "spending_limit",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "monthly_spent_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant_name", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="cards.virtualcard",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("card_name", models.CharField(max_length=64)),
                ("theme", models.CharField(default="teal-gold", max_length=16)),
                (
                    "issuance_fee",
                    models.DecimalField(decimal_places=2, default=5, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("issued", "Issued"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request",
                        to="cards.virtualcard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
