# Generated by Django 6.0.3 on 2026-08-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="kind",
            field=models.CharField(
                choices=[("transfer", "Transfer"), ("withdrawal", "Withdrawal")],
                db_index=True,
                default="transfer",
                max_length=20,
            ),
        ),
    ]
